---
version: '3'
services:
  # check http & tcp port
  nginx:
    image: nginx:1.16.0-alpine
    ports:
      - "8080:80"
  redis:
    image: redis:7.0.0
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
